# Generated by Django 5.0.7 on 2024-08-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labels',
            new_name='Label',
        ),
        migrations.RenameModel(
            old_name='Sprints',
            new_name='Sprint',
        ),
    ]
