# Generated by Django 5.0.7 on 2024-08-08 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_rename_labels_label_rename_sprints_sprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(editable=False, max_length=10)),
                ('description', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('sprint', models.ForeignKey(blank=True, help_text='Sprints to organize tasks within a timeframe.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='track.sprint')),
                ('status', models.ForeignKey(blank=True, help_text='Status of the task.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='track.taskstatus')),
            ],
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
