# Generated by Django 5.0.7 on 2024-08-27 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_task_delete_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, help_text='Sprints to organize tasks within a timeframe.', null=True, on_delete=django.db.models.deletion.CASCADE, to='track.sprint'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Status of the task.', null=True, on_delete=django.db.models.deletion.CASCADE, to='track.taskstatus'),
        ),
    ]
