# Generated by Django 5.0.7 on 2024-08-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_alter_task_sprint_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='key_id',
            field=models.CharField(max_length=10),
        ),
    ]
