# Generated by Django 5.0.7 on 2024-08-27 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_alter_task_key_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.profile'),
        ),
    ]
